language: c
sudo: false

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - mkdir -p ~/tmp
  - export PATH=~/.local/bin:$PATH
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.3/stack-1.6.3-linux-x86_64.tar.gz | tar xz -C ~/tmp
  - mv ~/tmp/stack-1.6.3-linux-x86_64/stack ~/.local/bin/
  - cd ${TRAVIS_BUILD_DIR}

matrix:
  include:
    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
    - env: GHCVER=8.0.1 STACK_YAML=stack-8.0.yaml
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}
    - env: GHCVER=8.2.2 STACK_YAML=stack-8.2.yaml
      addons: {apt: {packages: [ghc-8.2.2],sources: [hvr-ghc]}}
    - env: GHCVER=head STACK_YAML=stack-head.yaml
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
   - env: GHCVER=head STACK_YAML=stack-head.yaml

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
